// Test definitions. Do NOT edit this file!
#define CATCH_CONFIG_MAIN // defines main() automatically
#include <iostream>
#include "catch.hpp"
#include "main.hpp"
// tests for exercise 1
TEST_CASE("Ex1 makeNameRecord()", "[example]")
{
	const int N = 5000;
	string state[N];
	string gender[N];
	int year[N];
	string name[N];
	int count[N];
	int cnt;

	cnt = makeNameRecord(state, gender, year, name, count);
	cout << "****************************************\n";
	INFO("the number of lines in file is incorrect " << cnt);
	REQUIRE(cnt == 4080);
}
// tests for exercise 2
TEST_CASE("Ex2 findNames()", "[example]")
{
	const int N = 5000;
	string state[N];
	string gender[N];
	int year[N];
	string name[N];
	int count[N];
	int cnt;
	char starting = 'S';
	string stname = "CA";

	cnt = makeNameRecord(state, gender, year, name, count);
	cout << "****************************************\n";
	cnt = findNames(cnt, state, gender, year, name, count, starting, stname);

	INFO("the number of lines in file is incorrect " << cnt);
	REQUIRE(cnt == 11);
}
// tests for exercise 3
TEST_CASE("Ex3 findNames()", "[example]")
{
	const int N = 5000;
	string state[N];
	string gender[N];
	int year[N];
	string name[N];
	int count[N];
	int cnt;
	char starting = 'J';
	string stname = "TX";

	cnt = makeNameRecord(state, gender, year, name, count);
	cout << "****************************************\n";
	cnt = findNames(cnt, state, gender, year, name, count, starting, stname);

	INFO("the number of lines in file is incorrect " << cnt);
	REQUIRE(cnt == 10);
}
